### ISSUE TITLE
component_name not set when directly rendering a component

### ISSUE THREAD

**Issue by aaronwalker** [theonestack/cfhighlander#10]
If I try and use component_name inside a highlander component and when rendering the component directly (not nested) I get the following error

```
$ ../cfhighlander/bin/cfhighlander cfcompile ecs-services --validate
Trying to load ecs-services@latest from /Users/aaronwalker/Workspaces/theonestack/hl-component-ecs-services/ecs-services ... 
Trying to load ecs-services@latest from /Users/aaronwalker/Workspaces/theonestack/hl-component-ecs-services ... 
Processing higlander component ecs-services
	Location:/Users/aaronwalker/Workspaces/theonestack/hl-component-ecs-services/ecs-services.highlander.rb
	Config:{"log_retention"=>7, "cpu"=>1024, "memory"=>256, "task_definition"=>{"nginx"=>{"image"=>"nginx", "ports"=>[80]}}, "targetgroup"=>{"name"=>"DefaultHTTP", "container"=>"nginx", "port"=>80}}
/Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.dsl.base.rb:18:in `method_missing': #<Highlander::Dsl::Template:0x007fbb72de12c0>Unknown method or variable component_name in Highlander template (StandardError)
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.factory.rb:106:in `block in load'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.dsl.rb:419:in `instance_eval'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.dsl.rb:419:in `HighlanderComponent'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.factory.rb:102:in `load'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.factory.rb:102:in `eval'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/lib/highlander.factory.rb:102:in `load'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/bin/highlander.rb:154:in `build_component'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/bin/highlander.rb:75:in `cfcompile'
	from /Users/aaronwalker/.chefdk/gem/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/aaronwalker/.chefdk/gem/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/aaronwalker/.chefdk/gem/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/aaronwalker/.chefdk/gem/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/aaronwalker/Workspaces/theonestack/cfhighlander/bin/highlander.rb:158:in `<top (required)>'
	from ../cfhighlander/bin/cfhighlander:3:in `require_relative'
	from ../cfhighlander/bin/cfhighlander:3:in `<main>'
```

**Comment by toshke** [comment]
@aaronwalker implemented in https://github.com/theonestack/cfhighlander/pull/11. Closing this one as ecs-service component compiles - https://asciinema.org/a/gTyK640ohIh7ezekXjQsFCBws

```yaml
component_name: ecs-services
template_name: ecs-services
template_version: latest
description: ecs-service - ecs-services - latest

```
