### ISSUE TITLE
Error on compile due to new az_create_subnets method

### ISSUE THREAD

**Issue by Samseppiol** [theonestack/cfhighlander#105]
A change to the subnet helper method seems to cause intermittent issues with components requiring an earlier version of VPC. See stack trace below. 

Even though we are specifying component vpc@1.7.0, bastion component has a dependson vpc@1.2.0. The addition of tags to the helper methods seems to throw an error. 

``` 
      Component name:'vpc', template: 'vpc@1.7.0' do
        parameter name: 'DnsDomain', value: dns_domain
      end

      Component name:'bastion', template: 'bastion' do
        parameter name: 'DnsDomain', value: dns_domain
        parameter name: 'InstanceType', value: 't2.micro'
      end
```

VPC helper method changes: https://github.com/theonestack/hl-component-vpc/pull/18

``` cfndsl template for bastion written to /Users/jh/clients/gcs-cloudformation/out/cfndsl/bastion.compiled.cfndsl.rb
Traceback (most recent call last):
        24: from /Users/jh/.rbenv/versions/2.5.3/bin/cfcompile:23:in `<main>'
        23: from /Users/jh/.rbenv/versions/2.5.3/bin/cfcompile:23:in `load'
        22: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/bin/cfcompile:4:in `<top (required)>'
        21: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/bin/cfcompile:4:in `require_relative'
        20: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/bin/cfhighlander.rb:298:in `<top (required)>'
        19: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        18: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        17: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        16: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        15: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/bin/cfhighlander.rb:107:in `cfcompile'
        14: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/lib/cfhighlander.compiler.rb:151:in `compileCloudFormation'
        13: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/lib/cfhighlander.compiler.rb:151:in `each'
        12: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/lib/cfhighlander.compiler.rb:152:in `block in compileCloudFormation'
        11: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/lib/cfhighlander.compiler.rb:147:in `compileCloudFormation'
        10: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfhighlander-0.8.2/lib/cfhighlander.compiler.rb:123:in `evaluateCloudFormation'
         9: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.16.12/lib/cfndsl.rb:87:in `eval_file_with_extras'
         8: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.16.12/lib/cfndsl.rb:87:in `eval'
         7: from /Users/jh/clients/gcs-cloudformation/out/cfndsl/vpc.compiled.cfndsl.rb:14:in `eval_file_with_extras'
         6: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.16.12/lib/cfndsl.rb:93:in `CloudFormation'
         5: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.16.12/lib/cfndsl/jsonable.rb:204:in `declare'
         4: from /Users/jh/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cfndsl-0.16.12/lib/cfndsl/jsonable.rb:204:in `instance_eval'
         3: from /Users/jh/clients/gcs-cloudformation/out/cfndsl/vpc.compiled.cfndsl.rb:179:in `block in eval_file_with_extras'
         2: from /Users/jh/clients/gcs-cloudformation/out/cfndsl/vpc.compiled.cfndsl.rb:179:in `each'
         1: from /Users/jh/clients/gcs-cloudformation/out/cfndsl/vpc.compiled.cfndsl.rb:184:in `block (2 levels) in eval_file_with_extras'
/Users/jh/.cfhighlander/components/vpc/1.2.0/ext/cfndsl/az.rb:104:in `az_create_subnets': wrong number of arguments (given 6, expected 2..5) (ArgumentError) ```

**Comment by Guslington** [comment]
resolved with https://github.com/theonestack/cfhighlander/pull/113
