### ISSUE TITLE
Rate exceeded build issue

### ISSUE THREAD

**Issue by BlakeCramer** [theonestack/cfhighlander#72]
/usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': Rate exceeded (Aws::CloudFormation::Errors::Throttling)
	from /usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
	from /usr/local/bundle/gems/aws-sdk-core-3.21.0/lib/seahorse/client/request.rb:70:in `send_request'
	from /usr/local/bundle/gems/aws-sdk-cloudformation-1.4.0/lib/aws-sdk-cloudformation/client.rb:3504:in `validate_template'
	from /usr/local/bundle/gems/highlander-0.1.2/lib/highlander.validator.rb:40:in `validate_local'
	from /usr/local/bundle/gems/highlander-0.1.2/lib/highlander.validator.rb:29:in `block in validate'
	from /usr/local/bundle/gems/highlander-0.1.2/lib/highlander.validator.rb:17:in `each'
	from /usr/local/bundle/gems/highlander-0.1.2/lib/highlander.validator.rb:17:in `validate'
	from /usr/local/bundle/gems/highlander-0.1.2/bin/highlander.rb:84:in `cfcompile'
	from /usr/local/bundle/gems/highlander-0.1.2/bin/highlander.rb:105:in `cfpublish'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/bundle/gems/highlander-0.1.2/bin/highlander.rb:158:in `<top (required)>'
	from /usr/local/bundle/gems/highlander-0.1.2/bin/highlander:3:in `require_relative'
	from /usr/local/bundle/gems/highlander-0.1.2/bin/highlander:3:in `<top (required)>'
	from /usr/local/bundle/bin/highlander:23:in `load'
	from /usr/local/bundle/bin/highlander:23:in `<main>'

**Comment by toshke** [comment]
@BlakeCramer this looks like older cfhighlander version (named originally highlander), lookint at the stack trace. Throttling errors  were fixed by setting number of retries to 10 in latest release `0.6.0`
